version: "3.7"
services:

  dev:
    container_name: microservice-b
    hostname: microservice-b
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/apps/microservice-b
      - /apps/microservice-b/node_modules
    ports:
      - ${SERVER_PORT}:3000
    command: npm run start
